services:
  node:
    image: "node:22-alpine"
    user: "root"
    network_mode: "host"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: sh -c "yarn install --frozen-lockfile && yarn build && yarn start"
    restart: "on-failure"
