services:
  node:
    image: "node:22-alpine"
    user: "root"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports: 
      - 4000:4000
    command: sh -c "yarn install --frozen-lockfile && yarn build && yarn start"
